### ISSUE TITLE
fixes on phase 3

### ISSUE THREAD

**Issue by abdelazizElemary** [abdo-taha/udemy#1]
- Make the categories nav bar `python, excel, web development, ...etc` for the courses responsive on screen narrowed. items should be in col instead of row 
<img width="1440" alt="Screen Shot 2022-08-24 at 1 39 11 AM" src="https://user-images.githubusercontent.com/25887879/186284839-e7e6e34c-6603-4ca3-9efa-88985a03bfeb.png">

**Comment by abdo-taha** [comment]
![image](https://user-images.githubusercontent.com/37912108/186601017-5239cf59-761d-4c2c-925d-ed277ece9d76.png)
i hope it's good enough
